/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define the Mem_mgr application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/

#ifndef _mem_mgr_app_
#define _mem_mgr_app_

/*
** Includes
*/

#include "app_cfg.h"
#include "memory.h"
#include "mem_file.h"


/***********************/
/** Macro Definitions **/
/***********************/

/*
** Events
*/

#define MEM_MGR_INIT_APP_EID    (MEM_MGR_BASE_EID + 0)
#define MEM_MGR_NOOP_EID        (MEM_MGR_BASE_EID + 1)
#define MEM_MGR_EXIT_EID        (MEM_MGR_BASE_EID + 2)
#define MEM_MGR_INVALID_MID_EID (MEM_MGR_BASE_EID + 3)


/**********************/
/** Type Definitions **/
/**********************/


/******************************************************************************
** Command Packets
** - See EDS command definitions in mem_mgr.xml
*/


/******************************************************************************
** Telmetery Packets
** - See EDS command definitions in mem_mgr.xml
*/


/******************************************************************************
** MEM_MGR_Class
*/
typedef struct
{

   /* 
   ** App Framework
   */ 
    
   INITBL_Class_t  IniTbl; 
   CMDMGR_Class_t  CmdMgr;
   
   /*
   ** Command Packets
   */

 
   /*
   ** Telemetry Packets
   */
   
   MEM_MGR_StatusTlm_t  StatusTlm;
   
   /*
   ** MEM_MGR State & Contained Objects
   */ 
           
   uint32           PerfId;
   CFE_SB_PipeId_t  CmdPipe;
   CFE_SB_MsgId_t   CmdMid;
   CFE_SB_MsgId_t   SendStatusMid;
   
   MEMORY_Class_t   Memory;
   MEM_FILE_Class_t MemFile;
   
} MEM_MGR_Class_t;


/*******************/
/** Exported Data **/
/*******************/

extern MEM_MGR_Class_t  Mem_mgr;


/************************/
/** Exported Functions **/
/************************/


/******************************************************************************
** Function: MEM_MGR_AppMain
**
*/
void MEM_MGR_AppMain(void);


/******************************************************************************
** Function: MEM_MGR_NoOpCmd
**
*/
bool MEM_MGR_NoOpCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


/******************************************************************************
** Function: MEM_MGR_ResetAppCmd
**
*/
bool MEM_MGR_ResetAppCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


#endif /* _mem_mgr_ */
