/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define platform configurations for the Mem_mgr application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**   2. Compile-time configurations that are applied to each platform
**      deployment of this app.
**   3. These definitions should minimal and only contain parameters that
**      need to be configurable at compile time that allows users to tuned
**      the app for a particular platform. Use mem_mgr_mission_cfg.h
**      for compile-time parameters that need to be tuned at the mission
**      level across all platform deployments. Use app_cfg.h for compile-time
**      parameters that don't need to be configured when an app is deployed
**      but are useful to be parameterized for maintaining the app and use
**      the JSON initialization file for parameters that can be defined at
**      runtime.
**
*/
#ifndef _mem_mgr_platform_cfg_
#define _mem_mgr_platform_cfg_


/*
** Includes
*/

#include "mem_mgr_mission_cfg.h"


/*
** Platform Deployment Configurations
*/

#define MEM_MGR_PLATFORM_REV   0

#define MEM_MGR_INI_FILENAME   "/cf/mem_mgr_ini.json"

#define MEM_MGR_MAX_SYM_LEN  OS_MAX_SYM_LEN


// Maximum number of bytes that can be loaded into RAM with a single memory load command
#define MEM_MGR_MAX_LOAD_FILE_DATA_RAM (1024 * 1024)

//Maximum number of bytes that can be loaded into EEPROM with a single memory load command
#define MEM_MGR_MAX_LOAD_FILE_DATA_EEPROM (128 * 1024)


// Maximum number of bytes that can be written to a file from RAM with a single memory dump command
#define MEM_MGR_MAX_DUMP_FILE_DATA_RAM (1024 * 1024)

// Maximum number of bytes that can be written to a file from EEPROM with a single memory dump command
#define MEM_MGR_MAX_DUMP_FILE_DATA_EEPROM (128 * 1024)

// Maximum number of bytes for a symbol table file dump
#define MEM_MGR_MAX_DUMP_FILE_DATA_SYMTBL (128 * 1024)


// Maximum number of bytes that can be loaded into RAM with a single memory fill command
#define MEM_MGR_MAX_FILL_DATA_RAM (1024 * 1024)

// Maximum number of bytes loaded into EEPROM with a single memory fill command
#define MEM_MGR_MAX_FILL_DATA_EEPROM (128 * 1024)


/*
** Compile switch to include code for the optional MEM32 memory. If defined the
** code will be included, otherwise the code will be excluded.
*/
#define MEM_MGR_OPT_INCL_MEM_SIZE32

// Maximum number of bytes that can be loaded into MEM32 memory type from a single load file
#define MEM_MGR_MAX_LOAD_FILE_DATA_MEM32 (1024 * 1024)

// Maximum number of bytes that can be dumped from MEM32 memory type to a single dump file
#define MEM_MGR_MAX_DUMP_FILE_DATA_MEM32 (1024 * 1024)

// Maximum number of bytes that can be loaded into MEM32 memory type with a single memory fill command
#define MEM_MGR_MAX_FILL_DATA_MEM32 (1024 * 1024)



/*
** Compile switch to include code for the optional MEM16 memory. If defined the
** code will be included, therwise it will be excluded.
*/
#define MEM_MGR_OPT_INCL_MEM_SIZE16

// Maximum number of bytes that can be loaded into MEM16 memory type from a single load file.
#define MEM_MGR_MAX_LOAD_FILE_DATA_MEM16 (1024 * 1024)

// Maximum number of bytes that can be dumped from MEM16 memory type to a single dump file.
#define MEM_MGR_MAX_DUMP_FILE_DATA_MEM16 (1024 * 1024)

// Maximum number of bytes that can be loaded into MEM16 memory type with a single memory fill command.
#define MEM_MGR_MAX_FILL_DATA_MEM16 (1024 * 1024)



/*
** Compile switch to include code for the optional MEM8 memory. If defined the
** code will be included, otherwise the code will be excluded.
*/
#define MEM_MGR_OPT_INCL_MEM_SIZE8

// Maximum number of bytes that can be loaded into MEM8 memory type from a single load file.
#define MEM_MGR_MAX_LOAD_FILE_DATA_MEM8 (1024 * 1024)

// Maximum number of bytes that can be dumped from MEM8 memory type to a single dump file.
#define MEM_MGR_MAX_DUMP_FILE_DATA_MEM8 (1024 * 1024)

// Maximum number of bytes that can be loaded into MEM8 memory type with a single memory fill command.
#define MEM_MGR_MAX_FILL_DATA_MEM8 (1024 * 1024)



#endif /* _mem_mgr_platform_cfg_ */
